# -*- coding: utf-8 -*-
"""STATISTICS ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMqdW_3zyMoIVyI6xsJmP1f3RiEkw9gB

#Statistics Basics | Assignment

**Question 1: What is the difference between descriptive statistics and inferential statistics? Explain with examples.**

Answer: The main difference lies in what you are doing with the data: describing it or making predictions based on it.

**•	Descriptive Statistics** involves summarizing, organizing, and presenting data in a meaningful way. It describes the features of a specific dataset without making conclusions that go beyond the data itself.

**Example:** If a teacher calculates the average score of a class of 30 students on a math test, that is descriptive statistics. It describes only that specific class.

**•	Inferential Statistics** involves using a sample of data to make estimates, predictions, or generalizations about a larger population. It allows you to draw conclusions that extend beyond the immediate data.

**Example:** If a researcher surveys 100 voters to predict the outcome of a national election, that is inferential statistics. They are using a small sample to infer the behavior of the entire population.

**Question 2: What is sampling in statistics? Explain the differences between random and stratified sampling.**

**Answer:** Sampling is the process of selecting a subset of individuals or items from a larger population to estimate characteristics of the whole population. It is often impractical to survey every single member of a population, so a representative sample is used instead.

Difference between Random and Stratified Sampling:

**•	Simple Random Sampling:** Every member of the population has an equal chance of being selected. It is like picking names out of a hat. This minimizes bias but might not ensure representation of specific subgroups if the population is diverse.

**•	Stratified Sampling:** The population is divided into distinct subgroups (strata) based on specific characteristics (e.g., age, gender, income), and then samples are randomly selected from each stratum. This ensures that every subgroup is adequately represented in the final sample.

**Question 3: Define mean, median, and mode. Explain why these measures of central tendency are important.**

**Answer:** These are measures of "central tendency," meaning they describe the center or typical value of a dataset.

**•	Mean:** The arithmetic average. It is calculated by adding all values together and dividing by the count of values. It is useful for data without extreme outliers.

**•	Median: **The middle value when the data is sorted in order. If there is an even number of observations, it is the average of the two middle numbers. It is robust against outliers (e.g., in salary data).

**•	Mode:** The value that appears most frequently in the dataset. A dataset can have one mode, multiple modes, or no mode. It is useful for categorical data.

**Importance:** These measures provide a single summary figure that represents the entire dataset, making large amounts of data easier to understand, compare, and analyze. They help identify the "normal" or "average" behavior within a group.

**Question 4: Explain skewness and kurtosis. What does a positive skew imply about the data?**

**Answer:**

**•	Skewness:** Measures the asymmetry of the probability distribution of a dataset around its mean. It tells you if data leans to the left or right.

**•	Kurtosis:** Measures the "tailedness" of the distribution. It indicates whether the data has heavy tails (many outliers) or light tails (few outliers) compared to a normal distribution.

**Positive Skew (Right Skew):** A positive skew implies that the tail on the right side of the distribution is longer or fatter. The bulk of the data values (including the median and mode) are concentrated on the left. In a positively skewed distribution, the Mean is typically greater than the Median.

**•	Example:** Income distribution is often positively skewed because a small number of people earn significantly more than the average.

**Question 5: Implement a Python program to compute the mean, median, and mode of a given list of numbers.**

numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]
"""

import numpy as np
from scipy import stats

numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]

# Calculate Mean
mean_val = np.mean(numbers)

# Calculate Median
median_val = np.median(numbers)

# Calculate Mode
mode_result = stats.mode(numbers, keepdims=True)
mode_val = mode_result.mode[0]

print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Mode: {mode_val}")

"""**Question 6: Compute the covariance and correlation coefficient between the following two datasets provided as lists in Python.**

list_x = [10, 20, 30, 40, 50]

list_y = [15, 25, 35, 45, 60]

"""

import numpy as np

list_x = [10, 20, 30, 40, 50]
list_y = [15, 25, 35, 45, 60]

# Compute Covariance Matrix (returns a 2x2 matrix)
covariance_matrix = np.cov(list_x, list_y)
covariance = covariance_matrix[0, 1]

# Compute Correlation Coefficient Matrix (returns a 2x2 matrix)
correlation_matrix = np.corrcoef(list_x, list_y)
correlation = correlation_matrix[0, 1]

print(f"Covariance: {covariance}")
print(f"Correlation Coefficient: {correlation}")

"""**Question 7: Write a Python script to draw a boxplot for the following numeric list and identify its outliers. Explain the result.**

data = [12, 14, 14, 15, 18, 19, 19, 21, 22, 22, 23, 23, 24, 26, 29, 35]

"""

import matplotlib.pyplot as plt
import numpy as np

data = [12, 14, 14, 15, 18, 19, 19, 21, 22, 22, 23, 23, 24, 26, 29, 35]

# Create Boxplot
plt.boxplot(data)
plt.title("Boxplot of Data")
plt.ylabel("Values")
plt.show()

# Calculation to identify outliers programmatically
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

outliers = [x for x in data if x < lower_bound or x > upper_bound]
print(f"Outliers: {outliers}")

"""**Explanation of Result:** A boxplot visualizes the five-number summary: minimum, first quartile (Q1), median, third quartile (Q3), and maximum. Points lying beyond the "whiskers" (usually 1.5 * IQR) are considered outliers. In this dataset, if any point is significantly higher or lower than the rest of the distribution, it will appear as an individual dot.

**Question 8: You are working as a data analyst in an e-commerce company. The marketing team wants to know if there is a relationship between advertising spend and daily sales.**

**•	Explain how you would use covariance and correlation to explore this relationship.**

**•	Write Python code to compute the correlation between the two lists.**

advertising_spend = [200, 250, 300, 400, 500]

daily_sales = [2200, 2450, 2750, 3200, 4000]
"""

import numpy as np

advertising_spend = [200, 250, 300, 400, 500]
daily_sales = [2200, 2450, 2750, 3200, 4000]

# Compute Correlation
correlation_matrix = np.corrcoef(advertising_spend, daily_sales)
correlation = correlation_matrix[0, 1]

print(f"Correlation between Ad Spend and Sales: {correlation}")

"""**Explanation:** To understand the relationship, I would use Covariance to determine the direction of the relationship. A positive covariance indicates that as ad spend increases, sales tend to increase. However, covariance is not scaled, so it is hard to judge the strength. Therefore, I would primarily use the Correlation Coefficient (Pearson's r). This metric scales the covariance between -1 and 1.

**If r is close to +1:** Strong positive relationship (More spend = More sales).

**If r is close to 0:** No linear relationship.

**If r is close to -1:** Strong negative relationship.

**Question 9: Your team has collected customer satisfaction survey data on a scale of 1-10 and wants to understand its distribution before launching a new product.**

**Explain which summary statistics and visualizations (e.g. mean, standard deviation, histogram) you'd use.**

**Write Python code to create a histogram using Matplotlib for the survey data.**

survey_scores = [7, 8, 5, 9, 6, 7, 8, 9, 10, 4, 7, 6, 9, 8, 7]
"""

import matplotlib.pyplot as plt

survey_scores = [7, 8, 5, 9, 6, 7, 8, 9, 10, 4, 7, 6, 9, 8, 7]

# Create Histogram
plt.hist(survey_scores, bins=range(1, 12), edgecolor='black', align='left')
plt.title("Distribution of Customer Satisfaction Scores")
plt.xlabel("Score (1-10)")
plt.ylabel("Frequency")
plt.xticks(range(1, 11))
plt.grid(axis='y', alpha=0.75)
plt.show()

"""**Explanation of Statistics and Visualizations:**

**Mean & Median:** To find the average satisfaction score. If the data is skewed, the median will give a better "typical" user rating.

**Standard Deviation**: To see how consistent the feedback is. A low standard deviation means most customers agree on the rating; a high one implies polarized opinions.

**Histogram**: This is the best visualization to see the frequency distribution. It allows us to instantly see if the data is normal (bell curve), skewed (mostly high or mostly low scores), or bimodal (two groups of customers with different opinions).
"""